export default {
  routes:[{
    method:'GET',
    path:'/outlets/:outlet_id/users/invitation/:token',
    handler:'outlet.acceptInvitation',
    config:{
      auth:false,
      middlewares:['api::outlet.outlet','api::outlet.subscription']
    }
  },{
    method:'PUT',
    path:'/outlets/:outlet_id/users/:id',
    handler:'outlet.updateUser',
    config:{
      middlewares:['global::auth','api::outlet.outlet',{
        name:'api::outlet.roles',
        config:{
          roles:'User',
          action:'edit'
        }
      },'api::outlet.subscription']
    }
  },{
    method:'DELETE',
    path:'/outlets/:outlet_id/users/:id',
    handler:'outlet.deleteUser',
    config:{
      middlewares:['global::auth','api::outlet.outlet',{
        name:'api::outlet.roles',
        config:{
          roles:'User',
          action:'delete'
        }
      },'api::outlet.subscription']
    }
  },{
    method:'GET',
    path:'/outlets/:outlet_id/users',
    handler:'outlet.findUser',
    config:{
      middlewares:['global::auth','api::outlet.outlet',{
        name:'api::outlet.roles',
        config:{
          roles:'User',
          action:'view'
        }
      },'api::outlet.subscription']
    }
  },{
    method:'POST',
    path:'/outlets/:outlet_id/users',
    handler:'outlet.createUser',
    config:{
      middlewares:['global::auth','api::outlet.outlet',{
        name:'api::outlet.roles',
        config:{
          roles:'User',
          action:'add'
        }
      },'api::outlet.subscription']
    }
  }]
}