export default {
  prefix:'/ingredients',
  routes:[
    {
      method:'GET',
      path:'/:outlet_id/:id',
      handler:'ingredient.findOne',
      config:{
        middlewares:['global::auth','api::outlet.outlet','api::outlet.subscription']
      }
    },,{
      method:'PUT',
      path:'/:outlet_id/:id',
      handler:'ingredient.update',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Ingredient',
            action:'edit'
          }
        },'api::outlet.subscription']
      }
    },{
      method:'DELETE',
      path:'/:outlet_id/:id',
      handler:'ingredient.delete',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Ingredient',
            action:'delete'
          }
        },'api::outlet.subscription']
      }
    },
    {
      method:'POST',
      path:'/:outlet_id/bulk-delete',
      handler:'ingredient.bulkDelete',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Ingredient',
            action:'delete'
          }
        },'api::outlet.subscription']
      }
    },
    {
      method:'GET',
      path:'/:outlet_id',
      handler:'ingredient.find',
      config:{
        middlewares:['global::auth','api::outlet.outlet','api::outlet.subscription']
      }
    },{
      method:'POST',
      path:'/:outlet_id',
      handler:'ingredient.create',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Ingredient',
            action:'add'
          }
        },'api::outlet.subscription']
      }
    }
  ]
}