export default {
  prefix:'/stocks',
  routes:[
    {
      method:'GET',
      path:'/:outlet_id/:id',
      handler:'stock.findOne',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Stock',
            action:'view'
          }
        },'api::outlet.subscription']
      }
    },{
      method:'PUT',
      path:'/:outlet_id/:id',
      handler:'stock.update',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Stock',
            action:'edit'
          }
        },'api::outlet.subscription']
      }
    },{
      method:'GET',
      path:'/:outlet_id',
      handler:'stock.find',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Stock',
            action:'view'
          }
        },'api::outlet.subscription']
      }
    },{
      method:'POST',
      path:'/:outlet_id',
      handler:'stock.create',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Stock',
            action:'add'
          }
        },'api::outlet.subscription']
      }
    }
  ]
}