export default {
  prefix:'/wallets',
  routes:[
    {
      method:'POST',
      path:'/:toko_slug/withdraw',
      handler:'wallet.withdraw',
      config:{
        middlewares:['global::auth','api::toko.toko','api::toko.subscription']
      }
    },
    {
      method:'GET',
      path:'/:toko_slug/history',
      handler:'wallet.history',
      config:{
        middlewares:['global::auth','api::toko.toko','api::toko.subscription']
      }
    },
    {
      method:'GET',
      path:'/:toko_slug',
      handler:'wallet.findOne',
      config:{
        middlewares:['global::auth','api::toko.toko','api::toko.subscription']
      }
    },{
      method:'PUT',
      path:'/:toko_slug',
      handler:'wallet.update',
      config:{
        middlewares:['global::auth','api::toko.toko','api::toko.subscription']
      }
    },{
      method:'POST',
      path:'/:toko_slug',
      handler:'wallet.create',
      config:{
        middlewares:['global::auth','api::toko.toko','api::toko.subscription']
      }
    }
  ]
}