export default {
  prefix:'/callback',
  routes:[
    {
      method:'POST',
      path:'/callback-va/:type',
      handler:'transaction.callbackVA',
      config:{
        auth:false,
        middlewares:['api::transaction.xendit']
      }
    },{
      method:'POST',
      path:'/callback-ewallet',
      handler:'transaction.callbackEwallet',
      config:{
        auth:false,
        middlewares:['api::transaction.xendit']
      }
    },{
      method:'POST',
      path:'/callback-qr',
      handler:'transaction.callbackQr',
      config:{
        auth:false,
        middlewares:['api::transaction.xendit']
      }
    },{
      method:'POST',
      path:'/callback-withdraw',
      handler:'transaction.callbackSendMoney',
      config:{
        auth:false,
        middlewares:['api::transaction.xendit']
      }
    },
  ]
}