export default {
  prefix:'/promos',
  routes:[
    {
      method:'GET',
      path:'/:outlet_id/:id',
      handler:'promo.findOne',
      config:{
        middlewares:['global::auth','api::outlet.outlet','api::outlet.subscription']
      }
    },{
      method:'PUT',
      path:'/:outlet_id/:id',
      handler:'promo.update',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Promo',
            action:'edit'
          }
        },'api::outlet.subscription']
      }
    },{
      method:'DELETE',
      path:'/:outlet_id/:id',
      handler:'promo.delete',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Promo',
            action:'delete'
          }
        },'api::outlet.subscription']
      }
    },{
      method:'POST',
      path:'/:outlet_id/bulk-delete',
      handler:'promo.bulkDelete',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Promo',
            action:'delete'
          }
        },'api::outlet.subscription']
      }
    },
    {
      method:'GET',
      path:'/:outlet_id',
      handler:'promo.find',
      config:{
        middlewares:['global::auth','api::outlet.outlet','api::outlet.subscription']
      }
    },{
      method:'POST',
      path:'/:outlet_id',
      handler:'promo.create',
      config:{
        middlewares:['global::auth','api::outlet.outlet',{
          name:'api::outlet.roles',
          config:{
            roles:'Promo',
            action:'add'
          }
        },'api::outlet.subscription']
      }
    }
  ]
}