export default {
  prefix:'/supports',
  routes:[{
    method:'GET',
    path:'/detail/:support_id',
    handler:'support.findOne',
    config:{
      middlewares:['global::auth','api::support.support']
    }
  },{
    method:'POST',
    path:'/:support_id',
    handler:'support.reply',
    config:{
      middlewares:['global::auth','api::support.support']
    }
  },{
    method:'PUT',
    path:'/:support_id',
    handler:'support.update',
    config:{
      middlewares:['global::auth']
    }
  },{
    method:'GET',
    path:'/:support_id',
    handler:'support.findMessage',
    config:{
      middlewares:['global::auth','api::support.support']
    }
  },{
    method:'POST',
    path:'/',
    handler:'support.create',
    config:{
      middlewares:['global::auth']
    }
  },{
    method:'GET',
    path:'/',
    handler:'support.find',
    config:{
      middlewares:['global::auth']
    }
  }]
}